/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as ChatGiftIdRouteImport } from './routes/chat.$giftId'
import { Route as CabinetInsightsRouteImport } from './routes/cabinet.insights'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatGiftIdRoute = ChatGiftIdRouteImport.update({
  id: '/chat/$giftId',
  path: '/chat/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetInsightsRoute = CabinetInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => CabinetRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/cabinet/insights': typeof CabinetInsightsRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/cabinet/insights': typeof CabinetInsightsRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/cabinet/insights': typeof CabinetInsightsRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabinet'
    | '/set-password'
    | '/cabinet/insights'
    | '/chat/$giftId'
    | '/user/$userId'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabinet'
    | '/set-password'
    | '/cabinet/insights'
    | '/chat/$giftId'
    | '/user/$userId'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/cabinet'
    | '/set-password'
    | '/cabinet/insights'
    | '/chat/$giftId'
    | '/user/$userId'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetRoute: typeof CabinetRouteWithChildren
  SetPasswordRoute: typeof SetPasswordRoute
  ChatGiftIdRoute: typeof ChatGiftIdRoute
  UserUserIdRoute: typeof UserUserIdRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$giftId': {
      id: '/chat/$giftId'
      path: '/chat/$giftId'
      fullPath: '/chat/$giftId'
      preLoaderRoute: typeof ChatGiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/insights': {
      id: '/cabinet/insights'
      path: '/insights'
      fullPath: '/cabinet/insights'
      preLoaderRoute: typeof CabinetInsightsRouteImport
      parentRoute: typeof CabinetRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CabinetRouteChildren {
  CabinetInsightsRoute: typeof CabinetInsightsRoute
}

const CabinetRouteChildren: CabinetRouteChildren = {
  CabinetInsightsRoute: CabinetInsightsRoute,
}

const CabinetRouteWithChildren =
  CabinetRoute._addFileChildren(CabinetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetRoute: CabinetRouteWithChildren,
  SetPasswordRoute: SetPasswordRoute,
  ChatGiftIdRoute: ChatGiftIdRoute,
  UserUserIdRoute: UserUserIdRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
