/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as GiftGiftIdRouteImport } from './routes/gift.$giftId'
import { Route as ChatGiftIdRouteImport } from './routes/chat.$giftId'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftGiftIdRoute = GiftGiftIdRouteImport.update({
  id: '/gift/$giftId',
  path: '/gift/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatGiftIdRoute = ChatGiftIdRouteImport.update({
  id: '/chat/$giftId',
  path: '/chat/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/insights': typeof InsightsRoute
  '/set-password': typeof SetPasswordRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
  '/gift/$giftId': typeof GiftGiftIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/insights': typeof InsightsRoute
  '/set-password': typeof SetPasswordRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
  '/gift/$giftId': typeof GiftGiftIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/insights': typeof InsightsRoute
  '/set-password': typeof SetPasswordRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
  '/gift/$giftId': typeof GiftGiftIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabinet'
    | '/insights'
    | '/set-password'
    | '/chat/$giftId'
    | '/gift/$giftId'
    | '/user/$userId'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabinet'
    | '/insights'
    | '/set-password'
    | '/chat/$giftId'
    | '/gift/$giftId'
    | '/user/$userId'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/cabinet'
    | '/insights'
    | '/set-password'
    | '/chat/$giftId'
    | '/gift/$giftId'
    | '/user/$userId'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetRoute: typeof CabinetRoute
  InsightsRoute: typeof InsightsRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ChatGiftIdRoute: typeof ChatGiftIdRoute
  GiftGiftIdRoute: typeof GiftGiftIdRoute
  UserUserIdRoute: typeof UserUserIdRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/$giftId': {
      id: '/gift/$giftId'
      path: '/gift/$giftId'
      fullPath: '/gift/$giftId'
      preLoaderRoute: typeof GiftGiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$giftId': {
      id: '/chat/$giftId'
      path: '/chat/$giftId'
      fullPath: '/chat/$giftId'
      preLoaderRoute: typeof ChatGiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetRoute: CabinetRoute,
  InsightsRoute: InsightsRoute,
  SetPasswordRoute: SetPasswordRoute,
  ChatGiftIdRoute: ChatGiftIdRoute,
  GiftGiftIdRoute: GiftGiftIdRoute,
  UserUserIdRoute: UserUserIdRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
