/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatGiftIdRouteImport } from './routes/chat.$giftId'

const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatGiftIdRoute = ChatGiftIdRouteImport.update({
  id: '/chat/$giftId',
  path: '/chat/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/chat/$giftId': typeof ChatGiftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cabinet' | '/chat/$giftId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cabinet' | '/chat/$giftId'
  id: '__root__' | '/' | '/cabinet' | '/chat/$giftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetRoute: typeof CabinetRoute
  ChatGiftIdRoute: typeof ChatGiftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$giftId': {
      id: '/chat/$giftId'
      path: '/chat/$giftId'
      fullPath: '/chat/$giftId'
      preLoaderRoute: typeof ChatGiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetRoute: CabinetRoute,
  ChatGiftIdRoute: ChatGiftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
