// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Запасной путь: если getSession()/refresh не отдали токен (бывает при
// нестабильной связи с облачным auth-сервером), читаем сохранённую сессию
// прямо из localStorage — токен почти всегда там лежит.
function tokenFromStorage(): string | undefined {
  if (typeof localStorage === 'undefined') return undefined
  try {
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i)
      if (!k || !/^sb-.*-auth-token$/.test(k)) continue
      const raw = localStorage.getItem(k)
      if (!raw) continue
      const v = JSON.parse(raw)
      const tok = v?.access_token ?? v?.currentSession?.access_token
      if (typeof tok === 'string' && tok) return tok
    }
  } catch {
    /* noop */
  }
  return undefined
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | undefined
    try {
      const { data } = await supabase.auth.getSession()
      token = data.session?.access_token
      // Сессия есть, но токена нет (мог протухнуть, а автообновление не успело) —
      // пробуем обновить, чтобы запрос не ушёл без авторизации и не упал с
      // «No authorization header provided».
      if (!token) {
        const r = await supabase.auth.refreshSession()
        token = r.data.session?.access_token
      }
    } catch {
      /* оставляем token пустым — попробуем достать из хранилища ниже */
    }
    // Последний шанс: взять токен из localStorage (связь с облаком могла
    // подвести, но валидный токен уже лежит локально).
    if (!token) token = tokenFromStorage()
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)

