// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | undefined
    try {
      const { data } = await supabase.auth.getSession()
      token = data.session?.access_token
      // Сессия есть, но токена нет (мог протухнуть, а автообновление не успело) —
      // пробуем обновить, чтобы запрос не ушёл без авторизации и не упал с
      // «No authorization header provided».
      if (!token) {
        const r = await supabase.auth.refreshSession()
        token = r.data.session?.access_token
      }
    } catch {
      /* оставляем token пустым — ниже уйдёт без заголовка */
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
